### ISSUE TITLE
Exposing emails

### ISSUE THREAD

**Issue by Mange** [djalmaaraujo/gravatar-image#4]
Hi,

The main reason Gravatar wants an MD5 of email addresses is to no expose the user email to all visitors of the site. With this component, the email is always exposed for everyone.

I think the component should instead take the MD5 value directly, even though it becomes a lot less impressive.

Thoughts?

**Comment by djalmaaraujo** [comment]
Hi @Mange! Thanks for your suggestion. I just added the "hash" parameter. Now you can set username with the email OR use the hash. You just have to pass the md5 string directly.

**Comment by Mange** [comment]
Thanks a lot! :-D
